name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          config: ".markdownlint.yaml"
          globs: "**/*.md"

      - run: |
          pipx install poetry poethepoet
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: poetry

      - name: install
        run: poetry install

      - name: lint (ruff)
        run: poe lint --output-format=github

      - name: verifytypes (basedpyright)
        run: poe verifytypes

      # TODO: don't continue on error
      - name: stubtest (basedmypy)
        run: poe stubtest -- --concise
        continue-on-error: true

      - name: typetest
        run: poe typetest

      # TODO
      # - uses: scientific-python/repo-review@v0.11.2
      #   with:
      #     plugins: sp-repo-review
