name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  lint-and-typecheck:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          config: ".markdownlint.yaml"
          globs: "**/*.md"

      - run: |
          pipx install poetry poethepoet
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: poetry

      - name: install
        run: poetry install

      - name: lint
        run: poe lint --output-format=github

      - name: typetest
        run: poe typetest

      - name: typecheck (partial)
        run: |
          targets=(
            "_lib"
            "cluster"
            "constants"
            "datasets"
            "integrate"
            "interpolate"
            "io"
            "linalg"
            "misc"
            "ndimage"
            "odr"
            "spatial"
            "special"
          )
          for target in "${targets[@]}"; do
            poe mypy $target
            poe pyright $target
          done

  stubtest:
    needs: lint-and-typecheck
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pipx install poetry poethepoet

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: poetry

      - name: install
        run: poetry install

      - name: Run stubtest
        run: poe stubtest
