name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  lint-and-typecheck:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          config: ".markdownlint.yaml"
          globs: "**/*.md"

      - run: |
          pipx install poetry poethepoet
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: poetry

      - name: install
        run: poetry install

      - name: lint
        run: poe lint --output-format=github

      - name: typetest
        run: poe typetest

      - name: typecheck (partial)
        run: |
          targets=(
            "cluster"
            "constants"
            "datasets"
            "integrate"
            "interpolate"
            "io"
            "linalg"
            "misc"
            "ndimage"
            "odr"
            "special"
          )
          for target in "${targets[@]}"; do
            poe mypy $target
            poe pyright $target
          done

  stubtest:
    needs: lint-and-typecheck
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: [
          # "scipy._lib",
          "scipy.cluster",
          "scipy.constants",
          "scipy.datasets",
          "scipy.fft",
          "scipy.fftpack",
          "scipy.integrate",
          "scipy.interpolate",
          "scipy.io",
          "scipy.linalg",
          "scipy.misc",
          "scipy.ndimage",
          "scipy.odr",
          "scipy.optimize",
          # "scipy.signal",
          # "scipy.sparse",
          # "scipy.spatial",
          "scipy.special",
          # "scipy.stats",
        ]
    steps:
      - uses: actions/checkout@v4

      - run: pipx install poetry poethepoet

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: poetry

      - name: install
        run: poetry install

      - name: Run stubtest for ${{ matrix.module }}
        run: poe stubtest ${{ matrix.module }} -- --ignore-unused-allowlist

  stubtest-all:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pipx install poetry poethepoet

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: poetry

      - name: install
        run: poetry install

      - name: Run stubtest (ignored)
        run: poe stubtest -- --concise
        continue-on-error: true
